name: Deploy to WordPress.org
on:
  release:
    types: [published]

jobs:
  tag:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'

      - run: npm ci --prefer-offline --no-audit --no-fund

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build project
        run: npm run build
        env:
          CI: true

      - name: Run Playwright tests
        run: npx playwright test

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: pattern-css
