name: Plugin asset/readme update
on:
  push:
    branches:
      - main

jobs:
  trunk:
    name: Push to WordPress.org
    concurrency:
      group: ${{ github.workflow }} - ${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install and build
        run: |
          npm ci --prefer-offline --no-audit --no-fund
          npm run build
        env:
          CI: true

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        continue-on-error: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: pattern-css
